name: deploy code

on:
  workflow_run:
    workflows: ["terraform-setup"]
    types:
      - completed


permissions:
  actions: read
  contents: read


jobs:
  deployment:
    runs-on: ubuntu-latest
      
    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v4
        with:
          name: tf_vars
          github-token: ${{ github.token }}
          repository: ${{ github.repository }}
          run-id: ${{ github.event.workflow_run.id }}


      - name: View files
        run: ls


      - name: rsync deployments
        uses: burnett01/rsync-deployments@7.0.2
        with:
          switches: -avzr --delete --rsync-path="sudo rsync"
          path: app/
          remote_path: /var/www/html/
          remote_host: $(cat public_dns.txt)
          remote_user: ubuntu
          remote_key: ${{ secrets.PRIVATE_KEY_PAIR }}