name: deploy code

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
      
    steps:
      - uses: actions/checkout@v3
      - name: rsync deployments
        uses: burnett01/rsync-deployments@7.0.2
        with:
          switches: -avzr --delete
          path: app/
          remote_path: /var/www/html/
          remote_host: ec2-54-165-133-14.compute-1.amazonaws.com
          remote_user: ubuntu
          remote_key: ${{ secrets.PEM_KEY }}