name: deploy code

on:
  workflow_run:
    workflows: ["terraform-setup"]
    types:
      - completed


permissions:
  actions: read
  contents: read


jobs:
  deployment:
    runs-on: ubuntu-latest
      
    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v4
        with:
          name: tf_vars
          github-token: ${{ github.token }}
          repository: ${{ github.repository }}
          run-id: ${{ github.event.workflow_run.id }}


      - name: View files
        run: ls

      - name: Wait for Apache to be Ready (HTTP GET Check)
        env:
          SERVER_IP: $(cat public_dns.txt) # Or `localhost` if Apache is on the same runner
          APACHE_PORT: 80
          MAX_RETRIES: 20
          RETRY_DELAY: 5 # seconds
        run: |
          echo "Waiting for Apache to respond to HTTP requests at http://${SERVER_IP}:${APACHE_PORT}/..."
          for i in $(seq 1 $MAX_RETRIES); do
              HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" http://${SERVER_IP}:${APACHE_PORT}/)
              if [ "$HTTP_CODE" -eq 200 ]; then
                  echo "Apache is ready and serving content!"
                  break
              else
                  echo "Attempt $i/$MAX_RETRIES: Apache not responding (HTTP ${HTTP_CODE}). Retrying in ${RETRY_DELAY}s..."
                  sleep $RETRY_DELAY
              fi

              if [ $i -eq $MAX_RETRIES ]; then
                  echo "Error: Apache did not become ready within the allotted time."
                  exit 1
              fi
          done

      - name: rsync deployments
        uses: burnett01/rsync-deployments@7.0.2
        with:
          switches: -avzr --delete --rsync-path="sudo rsync"
          path: app/
          remote_path: /var/www/html/
          remote_host: $(cat public_dns.txt)
          remote_user: ubuntu
          remote_key: ${{ secrets.PRIVATE_KEY_PAIR }}