name: "terraform-setup"


on:
  push:
    branches:
      - main

jobs:
  infra:
    runs-on: ubuntu-latest 
    steps:
      - name: Get the repo
        uses: actions/checkout@v4.2.2
      - name: "files"
        run: ls

      - name: Set up terraform
        uses: hashicorp/setup-terraform@v3
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          aws-access-key-id: ${{ secrets.KEY_ID }}
          aws-secret-access-key: ${{ secrets.ACCESS_KEY }}
          aws-region: us-east-1

      - name: Initialize Terraform
        run: |
          cd infrastructure
          terraform init

      - name: Terraform plan
        run: |
          cd infrastructure
          terraform plan

      - name: Terraform apply
        run: |
          cd infrastructure
          terraform apply -auto-approve